### ISSUE TITLE
Extra Points

### ISSUE THREAD

**Issue by danipalli** [htl-perg-2018-19-4ahif/angular-todo-example-danipalli#1]
Dear Mr. Stropek,

i did both exercises to gain two additional extra points.
Do I have to upload my code to a website, or is my source code sufficient?

Kind regards
Daniel Pallinger

**Comment by rstropek** [comment]
Hi @danipalli!

Very well done 👍. Both extra exercises work exactly as expected. The two points are yours.

Greetings,
Rainer Stropek
